---

- hosts: web
  become: yes
  tasks:
    - name: Update package cache on Debian/Ubuntu
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update package cache on Amazon Linux/RedHat
      yum:
        update_cache: yes
      when: ansible_os_family != "Debian"

    - name: Install Docker on Debian/Ubuntu
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker on Amazon Linux/RedHat
      yum:
        name: docker
        state: present
      when: ansible_os_family != "Debian"

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: flask-app
        image: "{{ docker_image }}"
        ports:
          - "5000:5000"
        restart_policy: always
        state: started